
ARG BASE_IMAGE="registry.redhat.io/rhbk/keycloak-rhel9:22-7"
ARG SUMMARY="Custom RHBK Container with custom themes and FIPS libraries"
ARG NAME="Optimized RHBK Container Image"
ARG MAINTAINER="The Platform team <platformteam@test.org>"

FROM $BASE_IMAGE  as builder 
USER root

ARG BASE_IMAGE

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Enable scripts features
ENV KC_FEATURES=scripts,kerberos,fips,docker,authorization,client-secret-rotation,impersonation,token-exchange,web-authn

# Configure a database vendor
ENV KC_DB=postgres

# Configure default cache stack
ENV KC_CACHE_STACK=kubernetes

# Configure XA Transaction 
ENV KC_TRANSACTION_XA_ENABLED=true
ENV QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY=true

# ENABLE FIPS mode
ENV KC_FIPS_MODE=strict

# Add custom java security file to override default  
COPY _build/kcadm.java.security /tmp/kcadm.java.security
COPY _build/java.security /usr/lib/jvm/jre-17-openjdk/conf/security/java.security 
ADD  --chown=keycloak:keycloak _build/java.security  /opt/keycloak/conf 

# Add Bouncy Castle 
ADD --chown=keycloak:keycloak _build/extensions/*.jar /tmp/files/

# Add custom themes jar
#ADD --chown=keycloak:keycloak _build/extensions/custom-keycloak-themes.jar /tmp/files/custom-keycloak-themes.jar

WORKDIR /opt/keycloak

ENV KC_DB=postgres

# copy libraries to providers dir
RUN cp /tmp/files/*.jar /opt/keycloak/providers/

# copy libraries to jre dir
RUN cp /tmp/files/*.jar /usr/lib/jvm/jre-17-openjdk/lib/

# debug statements
RUN cat /usr/lib/jvm/jre-17-openjdk/conf/security/java.security | grep -v "#" | egrep "fips.|keystore"
RUN fips-mode-setup --enable

# Create BCFKS keystore
RUN export KC_OPTS="-Djava.security.properties=/usr/lib/jvm/jre-17-openjdk/conf/security/java.security -Dcom.redhat.fips=true" && \
    keytool -keystore /opt/keycloak/conf/server.keystore \
    -storetype bcfks \
    -providername BCFIPS \
    -providerclass org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider \
    -provider org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider \
    -providerpath /opt/keycloak/providers/bc-fips-1.0.2.3.jar \
    -alias localhost \
    -ext  "SAN:c=DNS:localhost,IP:127.0.0.1" \
    -genkeypair -sigalg SHA512withRSA -keyalg RSA -storepass passwordpassword \
    -dname CN=localhost -keypass passwordpassword \
    -J-Djava.security.properties=/tmp/kcadm.java.security

RUN /opt/keycloak/bin/kc.sh build  --features=fips,docker,authorization,client-secret-rotation,impersonation,token-exchange,web-authn --fips-mode=strict


FROM $BASE_IMAGE 

ARG BASE_IMAGE
ARG SUMMARY
ARG NAME
ARG MAINTAINER


LABEL summary="$SUMMARY" \
      description="$SUMMARY" \
      io.k8s.description="$SUMMARY" \
      io.k8s.display-name="$NAME" \
      name="$NAME" \
      version="1" \
      usage="podman run -it --rm --name my-rhbk-optimized-test localhost/fips-rhbk-keycloak-rhel9 bash " \
      maintainer="$MAINTAINER"

COPY --from=builder /opt/keycloak/ /opt/keycloak/
COPY --from=builder /usr/lib/jvm/jre-17-openjdk/conf/security/java.security /usr/lib/jvm/jre-17-openjdk/conf/security/java.security

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]

